### ISSUE TITLE
[Meta] Develop product content guidelines

### ISSUE THREAD

**Issue by florent-leborgne** [elastic/tech-writing-guidelines#10]
Objective: Help writers, designers and developers find consistent, complete and easy to consume guidelines for product content.

What is product content? UI copy, API text, product notifications and emails.
Where? At the moment, the EUI doc site is the best place to consolidate guidelines, content and code examples.

KRs:

- Easy to find guidelines for all UI components
- Good and bad examples to illustrate all rules
- UX Writers contribute regularly to EUI guidelines

Steps:

- [ ] [#98726](https://github.com/elastic/cloud/issues/98726)
- [ ] [#98727](https://github.com/elastic/cloud/issues/98727)
- [ ] [#99085](https://github.com/elastic/cloud/issues/99085)
- [ ] Assess current UI content state against updated writing guidelines to identify improvement opportunities

These can be considered a first step towards a unified content design system that will be ground work for more mature processes and content overall regarding product content. Some next steps could include backing up choices with content UX research, filling more gaps (accessibility & inclusivity, style, documented patterns...) or gathering + developing guidelines that sometimes already exist somewhere in Elastic.
